version: "3.8"

services:
  web:
    container_name: "most-ich-frontend"
    image: "node:16-alpine"
    working_dir: "/app"
    ports:
      - "8080:3000"
      - "24678:24678"
    volumes:
      - "../frontend:/app"
    command:
      - /bin/sh
      - -c
      - |
        npm install
        npm run dev